### ISSUE TITLE
Php error on line 55 of of Client.php

### ISSUE THREAD

**Issue by sams** [ornicar/php-github-api#10]
I changed the line from:

`$this->httpClient = $httpClient ?: new Github_HttpClient_Curl();`

to:

`$this->httpClient = ($httpClient === null) ? new Github_HttpClient_Curl() : $httpClient;`

https://github.com/ornicar/php-github-api/blob/master/lib/Github/Client.php#L55

before the change I had errors; it appears that syntax is OK in php6

**Comment by ornicar** [comment]
Fix PHP 5.2 compatibility - closed by 7f54c597e18083affe3177cefe8af6447552f1a7
