### ISSUE TITLE
getRawData returns blank response

### ISSUE THREAD

**Issue by WilHall** [ornicar/php-github-api#12]
When using the getRawData method of fetching a file from github, a blank response is returned.

Example code:

> $blob = $github->getObjectApi()->getRawData($git_username, $reponame, $sha);

I checked my variables ($git_username, $reponame, $sha) against an older version using the older API, and they are the same.

Also tried printing a response directly from inside Object.php in the API and response was still blank.

**Comment by ornicar** [comment]
You are probably requesting a wrong or incomplete sha. I added a functional test for your use case, and the test passes:
https://github.com/ornicar/php-github-api/commit/371ffd032c6255b16c55e12d3cfcaa17c05d3025
