### ISSUE TITLE
Pull Request API not covered

### ISSUE THREAD

**Issue by Paris** [ornicar/php-github-api#13]
The [pull request](http://develop.github.com/p/pulls.html) API is not implemented, which is something I need quite soon.

**Comment by ornicar** [comment]
Cool, I'm waiting for your pull request then :)

**Comment by jeanvoye** [comment]
Hi, 

I am half way done on this. I will give it some more love and drop a pull-request. 
@ all : in case anybody is tackling the subject, let us work together : https://github.com/jeanvoye/php-github-api

Thanks for this lib,
Cheers,

**Comment by ornicar** [comment]
It is covered now, thanks to @jeanvoye. Upgrade to version 3.2.
