### ISSUE TITLE
OAuth support

### ISSUE THREAD

**Issue by pulse00** [ornicar/php-github-api#22]
There's an oAuth branch which apparently has the code of the old API. Is this functionality also available in the master branch or does this need to be ported?

**Comment by ornicar** [comment]
I don't know. Is it still supported by Github? It's been a long time I've used this lib.

**Comment by pulse00** [comment]
it's still supported. i've tested it with the oAuth branch and i got the oAuth redirect process working. i'll port it and send you a PR.

**Comment by ornicar** [comment]
cool

**Comment by jameswilson** [comment]
It appears that v2 of the Github API have now been decommissioned, in favor of v3 which is purely OAuth based.

See the [blog post](https://github.com/blog/1090-github-api-moving-on).

This issue is probably now the most important one on the queue at this point.

**Comment by ornicar** [comment]
https://github.com/ornicar/php-github-api/commit/c4705f0b3c56da64059bf8b59d89540a2a698382
