### ISSUE TITLE
getWatchedRepos returns only 100 repos.

### ISSUE THREAD

**Issue by scratcher28** [ornicar/php-github-api#23]
Hi.
I have about 1000 repos in my watch list, 
but getWatchedRepos() returns only 100 repos.
Can it be fixed? Thanks.

**Comment by ornicar** [comment]
There is no limitation on php side https://github.com/ornicar/php-github-api/blob/master/lib/Github/Api/User.php#L113

So I guess it comes from GitHub http api, and there's few we can do.
