### ISSUE TITLE
v3 support

### ISSUE THREAD

**Issue by jwhitcraft** [ornicar/php-github-api#25]
Just wondering when/if this will every support the v3 api?

**Comment by dmyers** [comment]
Me too!

**Comment by jameswilson** [comment]
Duplicate of #22 (OAuth support).

**Comment by Enissay** [comment]
I just started using this 2 months ago... I've really no luck :( 
I hope v3 will be supported soon ...

**Comment by mdale** [comment]
+1

**Comment by sebilasse** [comment]
+2

**Comment by ornicar** [comment]
https://github.com/ornicar/php-github-api/commit/c4705f0b3c56da64059bf8b59d89540a2a698382
