### ISSUE TITLE
Querystring not properly encoded in phpGitHubApiRequest::doSend

### ISSUE THREAD

**Issue by mikeyp** [ornicar/php-github-api#3]
For some reason I couldn't get a successful authenticated request out, and found that http_build_query was producing a string in the form of:

<pre>
login=name&amp;token=etcetcetc...
</pre>

This seems to contradict the docs for http_build_query, but changing the call to:

<pre>
$queryString = utf8_encode(http_build_query($parameters, '', '&'));
</pre>

seemd to work okay.

**Comment by mikeyp** [comment]
Crap. Specifically I was getting the literal string &amp;amp; instead of a single &amp;.

**Comment by ornicar** [comment]
fixed possible issue on authenticated queries - Closed by 6be82031f30a82e8a5ab93c99537925804c8f469
