### ISSUE TITLE
HTTP 404: Not Found

### ISSUE THREAD

**Issue by alrik11es** [ornicar/php-github-api#32]
I cannot believe this, I had a working script a week ago with this code:

``` php
$github = new \Github_Client();
$tags = $github->getRepoApi()->getRepoTags('alrik11es', 'sPHPf');
```

But now i'm getting an exception saying "HTTP 404: Not Found" don't know what can be happened :S
I've also updated to the last php-github-api tag but nothing.

I get my script working by simply a try{}catch(){} but it's just a temporary solution until I find what happened here.

**Comment by ornicar** [comment]
GitHub API v2 is deprecated, check the updated readme https://github.com/ornicar/php-github-api
