### ISSUE TITLE
PHP Fatal error:  Class 'Github_Client' not found

### ISSUE THREAD

**Issue by zQueal** [ornicar/php-github-api#34]
I keep receiving a fatal php error when calling the `$github = new Github_Client();` variable.

``` php
require_once('/www/github/Autoloader.php');
Github_Autoloader::register();
$github = new Github_Client();

$users = $github->getUserApi()->search('xanza');
return $users;
```

`PHP Fatal error:  Class 'Github_Client' not found in /var/www/index.php on line 3`
Is the full error. Any advice?

**Comment by blazarecki** [comment]
I think it's mean the class `Github_Client` was not autoload.

Can you explain how you install php-github-api ? With composer ?

Thanks.
