### ISSUE TITLE
Showing a Specific Commit

### ISSUE THREAD

**Issue by borgenk** [ornicar/php-github-api#4]
I didn't find a method for getting a specific commit so I added this to phpGitHubApiCommit.php

public function getCommit($username, $repo, $branch, $path)
{
    $response = $this->api->get('commits/show/'.urlencode($username).'/'.urlencode($repo).'/'.urlencode($branch).'/'.urlencode($path));

```
return $response['commit'];
```

}

**Comment by ornicar** [comment]
Thanks, I will add this soon.

**Comment by ornicar** [comment]
It has been added, tested and documented :)

**Comment by kiall** [comment]
My new comment
